### ISSUE TITLE
TypeError: Uncaught error: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by Fingu** [timoweiss/collector-backend#3]
Hey,
ich steh wieder auf dem Schlauch..
Habe jetzt einen User, ein System, verschiedene Applications angelegt, .... und mal paar Daten generieren lassen. Wenn ich z.B. in der Neo4j-Db nachschaue schaut das alles soweit auch gut aus.
Jetzt wollte ich mal bisschen Daten auslesen aber bekomme keine. Bei den Traces bekomme ich als Response Body `[]` und Code 200 zurück. Bei metrics und graph einen `TypeError: Uncaught error: Cannot convert object to primitive value` . 

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot convert object to primitive value
    at isNaN (native)
    at /home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:216:16
    at Array.forEach (native)
    at describe (/home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:209:8)
    at processargs (/home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:113:17)
    at handle (/home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:304:15)
    at module.exports (/home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:312:10)
    at Object.parse_pattern [as parsePattern] (/home/fingu/Dokumente/collector-backend/api/node_modules/seneca/lib/common.js:44:10)
    at Seneca.api_act [as act] (/home/fingu/Dokumente/collector-backend/api/node_modules/seneca/seneca.js:861:23)
    at handler (/home/fingu/Dokumente/collector-backend/api/plugins/metrics/index.js:23:39)
connecting nodes: 3.216ms

Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot convert object to primitive value
    at isNaN (native)
    at /home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:216:16
    at Array.forEach (native)
    at describe (/home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:209:8)
    at processargs (/home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:113:17)
    at handle (/home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:304:15)
    at module.exports (/home/fingu/Dokumente/collector-backend/api/node_modules/norma/norma.js:312:10)
    at Object.parse_pattern [as parsePattern] (/home/fingu/Dokumente/collector-backend/api/node_modules/seneca/lib/common.js:44:10)
    at Seneca.api_act [as act] (/home/fingu/Dokumente/collector-backend/api/node_modules/seneca/seneca.js:861:23)
    at handler (/home/fingu/Dokumente/collector-backend/api/plugins/graphs/index.js:23:39)
```

Sagt dir das was? Oder denkst du es wäre möglich deine Versionen in Docker zu packen bzw. mir so mitzuteilen bei denen die Änderungen noch nicht waren? :o) 

Sorry dass ich schon wieder störe, hoffe das hat bald ein Ende :/

**Comment by jfinckh** [comment]
Hey, danke :D 

Mein ms-projekt zur Zeit ist das hier: [Calculator-Mesh](https://github.com/Fingu/MSTests/tree/master/Calculator-Mesh). Habe einen User angelegt, das system "Calculator" und dann die einzelnen applications "api-service", "divide-pin-service", ...  Dann den namen, die Applicationid und den Token in die einzelnen Files :)

**Comment by jfinckh** [comment]
Wer lesen kann ist klar im Vorteil.. Hatte statt "collector-host" "host" und dann statt an den localhost meine daten immer fleißig an 52.58.175.11 geschickt.. Oh man :D Sorry für den Stress, habs in [index](https://github.com/timoweiss/collector-backend/blob/master/api/index.js) in dem Kommentar auch mal geändert :)

**Comment by timoweiss** [comment]
hahah crap :D es liegt immer an solchen kleinen sachen :D 
happy hacking! 👍

**Comment by jfinckh** [comment]
Richtig dumm :D 
Danke, danke auch für deine Hilfe! :)
Schönes We noch :)

**Comment by timoweiss** [comment]
danke, gleichfalls ;)
